[workspace]
members = [
    "basis",
    "boys",
    "scf",
    "basis_set",
    "pointcloud",
    "chemfiles",
    "volumetric"
]
resolver = "2"

[profile.dev]
opt-level = 3

[profile.release]
debug = true
